version: '3.9'
services:
  ms-account:
    build:
      context: ./ms-account
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_USERNAME: java_user
      DB_PASSWORD: java_password
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - java-network

  ms-customer:
    build:
      context: ./ms-customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_USERNAME: java_user
      DB_PASSWORD: java_password
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - java-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - java-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: java_user
      POSTGRES_PASSWORD: java_password
      POSTGRES_DB: java_test
    ports:
      - "5432:5432"
    networks:
      - java-network

networks:
  java-network:
      POSTGRES_USER: java_test_user
      POSTGRES_PASSWORD: java_test_password
      POSTGRES_DB: test_java
    ports:
      - "5432:5432"
    networks:
      - java-network

networks:
  java-network:
    driver: bridge
