version: '3.9'
services:
  ms-account:
    build:
      context: ./ms-account
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - java-test-network

  ms-customer:
    build:
      context: ./ms-customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - java-test-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - java-test-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: java_test_user
      POSTGRES_PASSWORD: java_test_password
      POSTGRES_DB: test_java
    ports:
      - "5432:5432"
    networks:
      - java-test-network

networks:
  java-test-network:
    driver: bridge
